apiVersion: v1
kind: List
items:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: web
    labels:
      app: web
      app.kubernetes.io/instance: web
      app.kubernetes.io/name: nodejs
      app.kubernetes.io/part-of: web
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: web
        app.kubernetes.io/instance: web
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: web
          app.kubernetes.io/instance: web
          maistra.io/expose-route: "true"
      spec:
        containers:
          - name: web
            image: quay.io/mcouliba/web-nodejs:3.1_debugging
            ports:
              - containerPort: 8080
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: web
      app.kubernetes.io/instance: web
      app.kubernetes.io/part-of: web
    name: web
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: web
      app.kubernetes.io/instance: web
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: web
      app.kubernetes.io/instance: web
      app.kubernetes.io/name: nodejs
      app.kubernetes.io/part-of: web
    name: web
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: web
      weight: 100
    wildcardPolicy: None